name: aurora-serverless-cluster CI develop

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm i
      - name: Lint
        run: npm run lint:eslint .
      - name: Build
        run: npm run build
